{{- if eq .Values.core.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-core
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-core
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-core
      annotations:
        checksum/timescaledbSecret: {{ include (print $.Template.BasePath "/timescaledb/secret.yaml") . | sha256sum }}
        checksum/emqxInternalSecret: {{ include (print $.Template.BasePath "/emqx/internal/secret.yaml") . | sha256sum }}
        checksum/emqxExternalSecret: {{ include (print $.Template.BasePath "/emqx/external/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: core
          image: {{ .Values.core.image.name }}:{{ .Values.core.image.version }}
          ports:
            - name: core
              containerPort: 8080
          env:
            - name: AIIDA_PUBLIC_URL
              value: "{{ include "eclipse-aiida.core.external-host" . }}"

            - name: AIIDA_DB_URL
              value: jdbc:postgresql://{{ .Release.Name }}-timescaledb:5432/{{ .Values.timescaledb.database }}
            - name: AIIDA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-timescaledb-secret
                  key: username
            - name: AIIDA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-timescaledb-secret
                  key: password

            - name: AIIDA_INSTALLER_URL
              value: {{ .Values.core.installer.url }}

            - name: AIIDA_FEDERATOR_URL
              value: {{ .Values.core.federator.url }}

            - name: AIIDA_MESSAGE_BUS_INTERNAL_DB_URL
              value: jdbc:postgresql://{{ .Release.Name }}-timescaledb:5432/{{ .Values.internal.database }}
            - name: AIIDA_MESSAGE_BUS_INTERNAL_DB_SCHEMA
              value: {{ .Values.internal.databaseSchema }}
            - name: AIIDA_MESSAGE_BUS_INTERNAL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-internal-secret
                  key: databaseUsername
            - name: AIIDA_MESSAGE_BUS_INTERNAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-internal-secret
                  key: databasePassword
            - name: AIIDA_MESSAGE_BUS_INTERNAL_MQTT_HOST
              value: {{ .Release.Name }}-internal
            - name: AIIDA_MESSAGE_BUS_INTERNAL_MQTT_PORT
              value: {{ .Values.internal.ports.mqtt | quote }}
            - name: AIIDA_MESSAGE_BUS_INTERNAL_MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-internal-secret
                  key: mqttUsername
            - name: AIIDA_MESSAGE_BUS_INTERNAL_MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-internal-secret
                  key: mqttPassword

            - name: AIIDA_MESSAGE_BUS_EXTERNAL_DB_URL
              value: jdbc:postgresql://{{ .Release.Name }}-timescaledb:5432/{{ .Values.external.database }}
            - name: AIIDA_MESSAGE_BUS_EXTERNAL_DB_SCHEMA
              value: {{ .Values.external.databaseSchema }}
            - name: AIIDA_MESSAGE_BUS_EXTERNAL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-external-secret
                  key: databaseUsername
            - name: AIIDA_MESSAGE_BUS_EXTERNAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-external-secret
                  key: databasePassword
            - name: AIIDA_MESSAGE_BUS_EXTERNAL_MQTT_HOST
              value: {{ .Release.Name }}-external
            - name: AIIDA_MESSAGE_BUS_EXTERNAL_MQTT_PORT
              value: {{ .Values.external.ports.mqtt | quote }}
            - name: AIIDA_MESSAGE_BUS_EXTERNAL_MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-external-secret
                  key: mqttUsername
            - name: AIIDA_MESSAGE_BUS_EXTERNAL_MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-external-secret
                  key: mqttPassword

            {{- if .Values.core.loggingLevel.root }}
            - name: LOGGING_LEVEL_ROOT
              value: {{ .Values.core.loggingLevel.root }}
            {{- end }}
            {{- if .Values.core.loggingLevel.aiida }}
            - name: LOGGING_LEVEL_ENERGY_EDDIE_AIIDA_CORE
              value: {{ .Values.core.loggingLevel.aiida }}
            {{- end }}

            {{- if and (eq .Values.ingress.enabled true) .Values.core.path }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.core.path }}
            {{- end }}

      imagePullSecrets:
        - name: {{ .Values.ghcrImagePullSecrets.name }}
{{- end }}
