{{- if eq .Values.emqx.external.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-core-secret
spec:
  encryptedData:
    messageBusUsername:  {{ .Values.core.messageBus.db.encryptedUsername }}
    messageBusPassword:  {{ .Values.core.messageBus.db.encryptedPassword }}
  template:
    metadata:
      name: {{ .Release.Name }}-core-secret
    type: Opaque
{{- end }}