{{- if eq .Values.external.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external
spec:
  selector:
    app: {{ .Release.Name }}-external
  type: LoadBalancer
  ports:
    - name: mqtt
      port: {{ .Values.external.ports.mqtt }}
      targetPort: mqtt
    - name: mqtt-tls
      port: {{ .Values.external.ports.mqttTls }}
      targetPort: mqtt-tls
    - name: dashboard
      port: {{ .Values.external.ports.dashboard }}
      targetPort: dashboard
{{- end }}
