keycloak:
  image:
    name: quay.io/keycloak/keycloak
    version: 26.2

  secret:
    name: keycloak-secret
    postgres:
      usernameKey: postgres-username
      passwordKey: postgres-password

  postgres:
    image:
      name: postgres
      version: 17.6
    storageSize: 5Gi

  ingress:
    path: /iam

ingress:
  enabled: false
  host:
  path:
  tls:
    enabled: false
    clusterIssuer:
    secretName:
