{{- if eq .Values.core.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-core
  {{- include "eclipse-backend.core.labels" . | indent 2 }}
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-core
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-core
    spec:
      containers:
        - name: core
          image: {{ .Values.core.image.name }}:{{ .Values.core.image.version }}
          ports:
            - name: backend
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dockerized-backend
            {{- include "eclipse-backend.core.envs.context-path" . | indent 12 }}
            {{- include "eclipse-backend.core.envs.db" . | indent 12 }}
            {{- include "eclipse-backend.core.envs.cors" . | indent 12 }}
            {{- include "eclipse-backend.core.envs.eddie" . | indent 12 }}
            {{- include "eclipse-backend.core.envs.eddie-kafka" . | indent 12 }}
            {{- include "eclipse-backend.core.envs.keycloak" . | indent 12 }}
            {{- include "eclipse-backend.core.envs.mqtt" . | indent 12 }}
            {{- include "eclipse-backend.core.envs.tracing" . | indent 12 }}
            {{- include "eclipse-backend.customEnvs" .Values.core.customEnvs | indent 12 }}
          volumeMounts:
            - name: backend-truststore
              subPath: client.truststore.jks
              mountPath: /etc/certs/kafka/client.truststore.jks
              readOnly: true
      volumes:
        - name: backend-truststore
          secret:
            secretName: {{ .Values.core.kafka.sslTrustStoreSecret.name }}

      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
{{- end }}
