{{- if eq .Values.core.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-core
  {{- include "eclipse-backend.core.labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Release.Name }}-core
  ports:
    - name: backend
      targetPort: backend
      port: 8080
{{- end }}