ghcrImagePullSecrets:
  name: "ghcr-secret"

core:
  replicaCount: 1
  version: "latest"
  port: 8010
  overrideHostWithIp: false
  repositoryTrack: "stable"
  storageSize: "1Mi"

aiidaServices:
  namespace: "aiida-services"

aiida:

secrets:
  core:
    encryptedInstallerToken: "*"

  timescaledb:
    encryptedUsername: "*?"
    encryptedPassword: "*?"

  internal:
    encryptedDbUsername: "*?"
    encryptedDbPassword: "*?"
    encryptedMqttUsername: "*?"
    encryptedMqttPassword: "*?"
    encryptedDashboardUsername: "*?"
    encryptedDashboardPassword: "*?"

  external:
    encryptedDbUsername: "*?"
    encryptedDbPassword: "*?"
    encryptedMqttUsername: "*?"
    encryptedMqttPassword: "*?"
    encryptedDashboardUsername: "*?"
    encryptedDashboardPassword: "*?"