ghcrImagePullSecrets:
  name: "ghcr-secret"

core:
  replicaCount: 1
  version: "latest"
  port: 8010
  overrideHostWithIp: false
  repositoryTrack: "stable"
  storageSize: "1Mi"

aiidaServices:
  namespace: "aiida-services"

aiida:

secrets:
  core:
    encryptedInstallerToken: "*"
  timescaledb:
    encryptedUsername: "*?" # Only change during initial installation!
    encryptedPassword: "*?" # Only change during initial installation!
  emqx:
    encryptedSuperuserPassword: "*?" # Only change during initial installation!
    encryptedDatabasePassword: "*?" # Only change during initial installation!
  teleinfo2mqtt:
    encryptedMqttUsername: "*"
    encryptedMqttPassword: "*"
  keycloak:
    clientSecret: "*?" # Only change during initial installation!
    encryptedAdminUsername: "" # Only applied during initial installation
    encryptedAdminPassword: "" # Only applied during initial installation