{{- if eq .Values.timescaledb.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-timescaledb-secret
spec:
  encryptedData:
    username: {{ .Values.timescaledb.encryptedUsername }}
    password: {{ .Values.timescaledb.encryptedPassword }}
  template:
    metadata:
      name: {{ .Release.Name }}-timescaledb-secret
    type: Opaque
{{- end }}