{{- if eq .Values.timescaledb.enabled true }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-timescaledb
spec:
  replicas: {{ .Values.timescaledb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-timescaledb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-timescaledb
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/timescaledb/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/timescaledb/secret.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: timescaledb
          image: {{ .Values.timescaledb.image.name }}:{{ .Values.timescaledb.image.version }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.timescaledb.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-timescaledb-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-timescaledb-secret
                  key: password
            - name: INTERNAL_EMQX_DATABASE
              value: {{ .Values.internal.database }}
            - name: EXTERNAL_EMQX_DATABASE
              value: {{ .Values.external.database }}
          volumeMounts:
            - name: timescaledb-data
              mountPath: /var/lib/postgresql/data
            - name: timescaledb-config
              mountPath: /docker-entrypoint-initdb.d/00-replace_password_with_env.sh
              subPath: substitute-env.sh
            - name: timescaledb-config
              mountPath: /tmp/emqx-init-schema.sql
              subPath: emqx-init-schema.sql

          readinessProbe:
            tcpSocket:
              port: timescaledb

      volumes:
        - name: timescaledb-config
          configMap:
            name: {{ .Release.Name }}-timescaledb-config

  volumeClaimTemplates:
    - metadata:
        name: timescaledb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.timescaledb.storageSize }}
{{- end }}