{{- if and (eq .Values.ingress.enabled true) (eq .Values.ingress.tlsEnabled true) -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-cluster-issuer
spec:
  acme:
    email: developers@eclipse-digital.eu
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Release.Name }}-cluster-issuer
    solvers:
      - http01:
          ingress:
            class: traefik
{{- end -}}