{{- if eq .Values.ingress.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{- if eq .Values.ingress.tlsEnabled true }}
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-cluster-issuer
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ default "/" .Values.core.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-core
                port:
                  name: core

  {{- if eq .Values.ingress.tlsEnabled true }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Release.Name }}-tls
  {{- end }}

{{- end }}
