{{- if eq .Values.timescaledb.enabled true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-timescaledb-pvc
  {{- include "eclipse-backend.timescaledb.labels" . | indent 2 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.timescaledb.storageSize }}
{{- end }}
