{{- if eq .Values.timescaledb.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-timescaledb
  {{- include "eclipse-backend.timescaledb.labels" . | indent 2 }}
spec:
  replicas: {{ .Values.timescaledb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-timescaledb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-timescaledb
    spec:
      containers:
        - name: timescaledb
          image: {{ .Values.timescaledb.image.name }}:{{ .Values.timescaledb.image.version }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: eclipse-backend
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.timescaledb.secret.name }}
                  key: {{ .Values.timescaledb.secret.usernameKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.timescaledb.secret.name }}
                  key: {{ .Values.timescaledb.secret.passwordKey }}
            {{- if eq .Values.emqx.enabled true }}
            - name: ECLIPSE_MQTT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.emqx.secret.name }}
                  key: {{ .Values.emqx.secret.dbPasswordKey }}
            {{- end }}
            {{- include "eclipse-backend.customEnvs" .Values.timescaledb.customEnvs | indent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              subPath: init.sql
              mountPath: /tmp/init.sql
            - name: postgres-config
              subPath: replace-password-with-env.sh
              mountPath: /docker-entrypoint-initdb.d/00-replace_password_with_env.sh
      volumes:
        - name: postgres-config
          configMap:
            name: {{ .Release.Name }}-timescaledb-configmap
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-timescaledb-pvc
{{- end }}