apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-keycloak-postgres-pvc
  {{- include "eclipse-shared.keycloak.labels" . | indent 2 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.postgres.storageSize }}
