apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak-postgres
  {{- include "eclipse-shared.keycloak.labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Release.Name }}-keycloak-postgres
  ports:
    - port: 5432
