apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  {{- include "eclipse-shared.keycloak.labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Release.Name }}-keycloak
  ports:
    - name: keycloak
      port: 8080
      targetPort: keycloak
