apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- include "installer.core.labels" . | indent 2 }}
data:
  aiida-values.yaml: |
{{- toYaml .Values.aiida | nindent 4 }}
  secrets-template.yaml: |
{{- toYaml .Values.secrets | nindent 4 }}