apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  {{- include "installer.core.labels" . | indent 2 }}
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
    {{- include "installer.core.labels" . | indent 6 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/core/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: {{ .Release.Name }}
          image: "ghcr.io/eddie-energy/aiida-installer:{{ .Values.core.version }}"
          ports:
            - containerPort: {{ .Values.core.port }}
              name: core
          env:
            - name: REPOSITORY_TRACK
              value: "{{ .Values.core.repositoryTrack }}"
            - name: SERVICES_NAMESPACE
              value: "{{ .Values.aiidaServices.namespace }}"
            - name: OVERRIDE_HOST_WITH_IP
              value: "{{ .Values.core.overrideHostWithIp }}"
          readinessProbe:
            httpGet:
              path: /health
              port: core
          volumeMounts:
            - name: configmap
              mountPath: /src/configs/aiida-values.yaml
              subPath: aiida-values.yaml
            - name: configmap
              mountPath: /src/configs/secrets-template.yaml
              subPath: secrets-template.yaml
            - name: pvc
              mountPath: /src/data

      volumes:
        - name: configmap
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc

      imagePullSecrets:
        - name: {{ .Values.ghcrImagePullSecrets.name }}