apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  {{- include "installer.core.labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: core
      port: {{ .Values.core.port }}
      targetPort: core