timescaledb:
  replicaCount: 1
  storageSize: 5Gi
  image:
    name: timescale/timescaledb
    version: 2.21.1-pg17
  secret:
    name: timescaledb-secret
    usernameKey: username
    passwordKey: password

