imagePullSecret:
  name: ghcr-secret

keycloak:
  internalHost:
  externalHost:
  realm:

ingress:
  enabled: false
  host:
  path:
  tls:
    enabled: false
    clusterIssuer:
    secretName:

core:
  enabled: true
  replicaCount: 1
  corsAllowedOrigins:
  eddie:
   id:
   publicUrl:
   vhdDataNeedId:
   permissionMonitorSchedule: "0 0 18 * * *"
  keycloak:
    clientId:
  kafka:
    bootstrapServers:
    groupId: eclipse-backend
    clientId: eclipse-backend
    saslSecret:
      name: core-kafka-secret
      usernameKey: username
      passwordKey: password
    sslTrustStoreSecret:
      name: core-truststore-secret
      passwordKey: password
    messageFormat: xml
    cim:
      permissionVersion: cim_0_82
      vhdVersion: cim_0_82
      rtrVersion: cim_0_91_08
  tracing:
    url:
  image:
    name: ghcr.io/eclipse-energy/eclipse-backend
    version: latest
  customEnvs:

timescaledb:
  enabled: true
  replicaCount: 1
  storageSize: 5Gi
  image:
    name: timescale/timescaledb
    version: 2.21.1-pg17
  secret:
    name: timescaledb-secret
    usernameKey: username
    passwordKey: password
  customEnvs:

emqx:
  enabled: true
  replicaCount: 1
  storageSize: 3Gi
  externalPortTLS: 8883
  externalPortMTLS: 8884
  secret:
    name: emqx-secret
    mqttPasswordKey: mqttPassword
    dbPasswordKey: dbPassword
    sslKeyKey: server.key
  image:
    name: emqx/emqx
    version: 6.1.0
  customEnvs:
