{{- if eq .Values.internal.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-internal
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-internal
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/emqx/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/emqx/internal/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: emqx
          args: ["/bin/sh", "/tmp/substitute-env.sh"]
          image: {{ .Values.internal.image.name }}:{{ .Values.internal.image.version }}
          ports:
            - name: mqtt
              containerPort: 1883
            - name: mqtt-tls
              containerPort: 8883
            - name: dashboard
              containerPort: 18083
          env:
            - name: AUTH_SERVER
              value: {{ .Release.Name }}-timescaledb:5432
            - name: AUTH_DATABASE
              value: {{ .Values.internal.database }}
            - name: AUTH_SCHEMA
              value: {{ .Values.internal.databaseSchema }}
            - name: AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-internal-secret
                  key: databaseUsername
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-internal-secret
                  key: databasePassword
            - name: DASHBOARD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-internal-secret
                  key: dashboardUsername
            - name: DASHBOARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-internal-secret
                  key: dashboardPassword
          volumeMounts:
            - name: emqx-config
              mountPath: /tmp/base.hocon
              subPath: base.hocon
            - name: emqx-config
              mountPath: /tmp/substitute-env.sh
              subPath: substitute-env.sh

          readinessProbe:
            tcpSocket:
              port: dashboard

      volumes:
        - name: emqx-config
          configMap:
            name: {{ .Release.Name }}-emqx-configmap
{{- end }}
