{{- if eq .Values.emqx.external.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-emqx-external
spec:
  selector:
    app: {{ .Release.Name }}-emqx-external
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
    - name: mqtt-tls
      port: 8883
      targetPort: mqtt-tls
    - name: dashboard
      port: 18083
      targetPort: dashboard
{{- end }}
