{{- if eq .Values.internal.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-internal
spec:
  selector:
    app: {{ .Release.Name }}-internal
  type: LoadBalancer
  ports:
    - name: mqtt
      port: {{ .Values.internal.ports.mqtt }}
      targetPort: mqtt
    - name: mqtt-tls
      port: {{ .Values.internal.ports.mqttTls }}
      targetPort: mqtt-tls
    - name: dashboard
      port: {{ .Values.internal.ports.dashboard }}
      targetPort: dashboard
{{- end }}
