ghcrImagePullSecrets:
  name: ghcr-secret

ingress:
  enabled: true
  host: localhost
  tlsEnabled: false

core:
  enabled: true
  replicaCount: 1
  image:
    name: ghcr.io/eclipse-energy/eclipse-aiida
    version: latest
  path:
  installer:
    url: "http://aiida-installer:8010"
  federator:
    url: "https://eclipse-dev.projekte.fh-hagenberg.at/federator"
  encryptedInstallerToken: ""
  loggingLevel:
    root:
    aiida:

timescaledb:
  enabled: true
  replicaCount: 1
  storageSize: 5Gi
  image:
    name: timescale/timescaledb
    version: 2.21.1-pg17
  service:
    type: ClusterIP
  database: aiida-core
  encryptedUsername: ""
  encryptedPassword: ""

internal:
  enabled: true
  replicaCount: 1
  storageSize: 3Gi
  image:
    name: emqx/emqx
    version: 5.8.6
  ports:
    mqtt: 1883
    mqttTls: 8883
    dashboard: 18083
  database: emqx_internal_db
  databaseSchema: internal
  encryptedDbUsername: ""
  encryptedDbPassword: ""
  encryptedMqttUsername: ""
  encryptedMqttPassword: ""
  encryptedDashboardUsername: ""
  encryptedDashboardPassword: ""

external:
  enabled: true
  replicaCount: 1
  storageSize: 3Gi
  image:
    name: emqx/emqx
    version: 5.8.6
  ports:
    mqtt: 1884
    mqttTls: 8884
    dashboard: 18084
  database: emqx_external_db
  databaseSchema: external
  encryptedDbUsername: ""
  encryptedDbPassword: ""
  encryptedMqttUsername: ""
  encryptedMqttPassword: ""
  encryptedDashboardUsername: ""
  encryptedDashboardPassword: ""
