ghcrImagePullSecrets:
  name: ghcr-secret

ingress:
  enabled: true
  host: localhost
  tlsEnabled: false

core:
  enabled: true
  replicaCount: 1
  image:
    name: ghcr.io/eclipse-energy/eclipse-aiida
    version: latest
  path:
  marketplace:
    federatorUrl: "https://marketplace.eclipse-aiida.org/federator"
  encryptedInstallerToken: ""
  loggingLevel:
    root:
    aiida:

timescaledb:
  enabled: true
  replicaCount: 1
  storageSize: 5Gi
  image:
    name: timescale/timescaledb
    version: 2.21.1-pg17
  database: aiida-core
  encryptedUsername: ""
  encryptedPassword: ""

internal:
  enabled: true
  replicaCount: 1
  storageSize: 3Gi
  image:
    name: emqx/emqx
    version: 5.8.6
  database: emqx_internal_db
  databaseSchema: internal
  encryptedDbUsername: ""
  encryptedDbPassword: ""
  encryptedMqttUsername: ""
  encryptedMqttPassword: ""
  encryptedDashboardUsername: ""
  encryptedDashboardPassword: ""

external:
  enabled: true
  replicaCount: 1
  storageSize: 3Gi
  image:
    name: emqx/emqx
    version: 5.8.6
  database: emqx_external_db
  databaseSchema: external
  encryptedDbUsername: ""
  encryptedDbPassword: ""
  encryptedMqttUsername: ""
  encryptedMqttPassword: ""
  encryptedDashboardUsername: ""
  encryptedDashboardPassword: ""
