ghcrImagePullSecrets:
  name: ghcr-secret

ingress:
  enabled: false
  host:
  tlsEnabled:

core:
  enabled: true
  replicaCount: 1
  image:
    name: ghcr.io/eclipse-energy/eclipse-aiida
    version: latest
  path:
  marketplace:
    federatorUrl: "https://marketplace.eclipse-aiida.org/federator"
  messageBus:
    db:
      encryptedUsername: ""
      encryptedPassword: ""
  customEnvs:

timescaledb:
  enabled: true
  replicaCount: 1
  storageSize: 5Gi
  image:
    name: timescale/timescaledb
    version: 2.21.1-pg17
  database: aiida-core
  encryptedUsername: ""
  encryptedPassword: ""
  customEnvs:

emqx:
  internal:
    enabled: true
    replicaCount: 1
    storageSize: 3Gi
    image:
      name: emqx/emqx
      version: 5.8.6
    db:
      database: emqx_internal_db
      schema: internal
      encryptedUsername: ""
      encryptedPassword: ""
    mqtt:
      encryptedUsername: ""
      encryptedPassword: ""
    dashboard:
      encryptedUsername: ""
      encryptedPassword: ""
  external:
    enabled: true
    replicaCount: 1
    storageSize: 3Gi
    image:
      name: emqx/emqx
      version: 5.8.6
    db:
      database: emqx_external_db
      schema: external
      encryptedUsername: ""
      encryptedPassword: ""
    mqtt:
      encryptedUsername: ""
      encryptedPassword: ""
    dashboard:
      encryptedUsername: ""
      encryptedPassword: ""
