apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  {{- include "federator.postgres.labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - port: 5432