{{- if eq .Values.timescaledb.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-timescaledb-secret
type: Opaque
stringData:
  username: {{ .Values.timescaledb.username | quote }}
  password: {{ .Values.timescaledb.password | quote  }}
{{- end }}