{{- if eq .Values.timescaledb.enabled true }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-timescaledb
spec:
  replicas: {{ .Values.timescaledb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-timescaledb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-timescaledb
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/timescaledb/secret.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: timescaledb
          image: {{ .Values.timescaledb.image.name }}:{{ .Values.timescaledb.image.version }}
          ports:
            - name: timescaledb
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.timescaledb.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-timescaledb-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-timescaledb-secret
                  key: password
          readinessProbe:
            tcpSocket:
              port: timescaledb

  volumeClaimTemplates:
    - metadata:
        name: timescaledb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.timescaledb.storageSize }}
{{- end }}