{{- if eq .Values.emqx.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-emqx
  {{- include "eclipse-backend.emqx.labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Release.Name }}-emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
    - name: mqtt-tls
      port: 8883
      targetPort: mqtt-tls
    - name: dashboard
      port: 18083
      targetPort: dashboard
{{- end }}
